parserOptions:
  sourceType: script
env:
  es2022: true
  browser: true
extends:
  - 'eslint:recommended'
rules:
  # FIXME: remove below rules
  no-var: off
  no-unused-vars: off
overrides:
  - files: '**/*.js'
    env:
      node: true
  - files: ['**/*.ts', '**/*.tsx']
    parser: '@typescript-eslint/parser'
    parserOptions:
      sourceType: module
      project: ['tsconfig.json']
    plugins: ['@typescript-eslint']
    extends:
      - 'plugin:@typescript-eslint/strict'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    rules:
      # FIXME: remove below rules
      no-var: off
      prefer-const: off
      no-useless-escape: off
      no-case-declarations: off
      '@typescript-eslint/prefer-includes': off
      '@typescript-eslint/no-unsafe-return': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unnecessary-condition': off
      '@typescript-eslint/consistent-type-assertions': off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/consistent-type-definitions': off
      '@typescript-eslint/consistent-indexed-object-style': off
      '@typescript-eslint/no-unsafe-call': off
      '@typescript-eslint/no-misused-promises': off
      '@typescript-eslint/no-unsafe-argument': off
      '@typescript-eslint/no-dynamic-delete': off
      '@typescript-eslint/dot-notation': off
      '@typescript-eslint/restrict-plus-operands': off
      '@typescript-eslint/ban-types': off
      '@typescript-eslint/unbound-method': off
      '@typescript-eslint/no-unnecessary-type-arguments': off
      '@typescript-eslint/ban-ts-comment': off
      '@typescript-eslint/prefer-ts-expect-error': off
      '@typescript-eslint/prefer-optional-chain': off
