version: '3'
services:
  build-worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    volumes:
      - ./worker:/home/worker:ro
      - ./worker-dist:/home/worker-dist
    stdin_open: true
    tty: true
  serve-webpack-example:
    build:
      context: .
      dockerfile: ./example/webpack-example/Dockerfile
    stdin_open: true
    tty: true
  test:
    depends_on:
      - serve-webpack-example
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    volumes:
      - ./demo-dist:/app/demo-dist:ro
      - ./playwright.config.ts:/app/playwright.config.ts:ro
      - ./tests:/app/tests
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    command: npx playwright test
  update-snapshots:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    volumes:
      - ./demo-dist:/app/demo-dist:ro
      - ./playwright.config.ts:/app/playwright.config.ts:ro
      - ./tests:/app/tests
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    command: npx playwright test --update-snapshots
