name: CI
on: workflow_call
permissions: {}
jobs:
  generateChangelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
          fetch-depth: 0 # fetch all reachable commits
          filter: tree:0 # while fetching trees and blobs on-demand

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: 'package.json'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Generate changelog
        run: npm run changelog > changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload npm folder
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: ./changelog.txt
